export const TYPES = {
  AuthController: Symbol.for("authController"),
  AuthService: Symbol.for("authService"),
  UserController: Symbol.for("usercontroller"),
  UserService: Symbol.for("userservice"),
  CategoryService: Symbol.for("categoryservice"),
  CategoryController: Symbol.for("categorycontroller"),
  ItemController: Symbol.for("itemcontroller"),
  ItemService: Symbol.for("itemservice"),
  OrderService: Symbol.for("orderservice"),
  OrderController: Symbol.for("ordercontroller"),
  ReservationController: Symbol.for("reservationcontroller"),
  ReservationService: Symbol.for("reservationservice"),
  OrderDetailController: Symbol.for("OrderDetailController"),
  OrderDetailService: Symbol.for("OrderDetailService"),
  PaymentService: Symbol.for("PaymentService"),
  PaymentController: Symbol.for("PaymentController"),
  TableController: Symbol.for("TableController"),
  TableService: Symbol.for("TableService"),
  PassportConfig: Symbol.for("PassportConfig"),
};
